[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v --tb=short --ignore=__init__.py
norecursedirs = .git __pycache__ .pytest_cache src/ui src/pipeline
filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning
